### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by fizolas** [artem78/s60-maps#46] opened 2022-02-22 10:20 UTC
Hi there Artem,

The following small bug is in 1.7.2 (probably it was there in previous versions as well...):

Launch s60maps. Now click on the menu and select a landmark: the landmark area will be very briefly displayed, but almost immediately the view will return to your current GPS location, which is not the expected behaviour.

Now close s60maps and open it again. Before doing the same thing as above, move your position using the cursor to somewhere slightly away from your current GPS location. If you choose a landmark now everything works as intended. The only difference is that the "Follow me" option appears now at the top of the menu, whereas it does not appear when you just open the menu without changing your position with the cursor.

Perhaps you could have the "Follow me" option always in the menu, with an "on" or "off" mark (or a tick mark) depending on the status.

All the best.

**Comment by artem78** [comment] 2022-03-01 14:05
1 - Thank you for the report. I'll try to fix this in next update.

2 - This is not a bug: when application already following your position 
this menu item is not neccesary.

> Perhaps you could have the "Follow me" option always in the menu, with an 
> "on" or "off" mark (or a tick mark) depending on the status.

I can make this if you wish.

**Comment by artem78** [comment] 2022-03-01 14:54
Due to documentation checkboxes not allowed in main menu (only in submenus). Therefore it is possible only to add on/off text.

**Comment by fizolas** [comment] 2022-03-01 15:46
Hi, I know, it is not really a bug, but it may be confusing to a new user.

By default the application is following your position, with the result that if you choose a landmark from the menu the application will keep following your position instead of staying at the chosen landmark. 

If you move away from your current position the application stops following you, and then you can go to the chosen landmark (until you select "follow me" again).

So, perhaps the simplest solution would be automatically deactivating "follow me" every time a landmark is chosen.

**Comment by artem78** [comment] 2022-03-11 10:12
> Launch s60maps. Now click on the menu and select a landmark: the landmark area will be very briefly displayed, but almost immediately the view will return to your current GPS location, which is not the expected behaviour.

Fixed in [v1.8](https://github.com/artem78/s60-maps/releases/tag/v1.8)

**Closed** 2022-03-11 10:17 UTC
Labels: bug
